@CT.API_HostAddress = https://localhost:7241

GET {{CT.API_HostAddress}}/Products?count=2
Accept: application/json

###

@name login

post {{CT.API_HostAddress}}/Account/SignIn
Accept: application/json
Content-Type: application/json

{
    "email": "test@test.com",
    "password": "1qaz@WSX"
}

###

@authToken = {{login.response.body.accessToken}}

GET {{CT.API_HostAddress}}/Account/GetCurrentUserData
Accept: application/json
Authorization: Bearer {{authToken}}

###
@name signup

POST {{CT.API_HostAddress}}/Account/SignUp
Accept: application/json
Content-Type: application/json

{
    "email": "test2@test.com",
    "password": "1qaz@WSX",
    "name": "Test",
    "defaultPhone": "+1234567890",
    "defaultAddress": "123 Main St, City, Country"
}

###
