@CT.API_HostAddress = https://localhost:7241/api

### Get products list
GET {{CT.API_HostAddress}}/products?count=10
Accept: application/json

### Register new user
POST {{CT.API_HostAddress}}/auth/register
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "1qaz@WSX",
  "name": "Test User",
  "defaultPhone": "+1234567890",
  "defaultAddress": "123 Test Street, Test City"
}

### User login
# @name login
POST {{CT.API_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "1qaz@WSX"
}

### Save token from response
@authToken = {{login.response.body.$.accessToken}}

### Get user info
GET {{CT.API_HostAddress}}/auth/info
Authorization: Bearer {{authToken}}

### User logout
POST {{CT.API_HostAddress}}/auth/logout
Authorization: Bearer {{authToken}}